# Generated by Django 4.2.14 on 2024-07-24 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        choices=[
                            ("M", "Matrícula"),
                            ("C", "Número de Chasis"),
                            ("V", "Número de VIN"),
                        ],
                        max_length=1,
                    ),
                ),
                ("numero_identificacion", models.CharField(max_length=50)),
                ("nombre_solicitante", models.CharField(max_length=100)),
                ("email_solicitante", models.EmailField(max_length=254)),
                (
                    "archivo_matricula",
                    models.FileField(upload_to="archivos/matriculas/"),
                ),
                ("archivo_licencia", models.FileField(upload_to="archivos/licencias/")),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="Pendiente", max_length=20)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
