# Generated by Django 4.2.14 on 2024-07-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="carnet_seguro",
            field=models.ImageField(
                blank=True, null=True, upload_to="archivos/carnets/"
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="comentario",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="fecha_emision",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="fecha_expiracion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="numero_poliza",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("En Proceso", "En Proceso"),
                    ("Aprobado", "Aprobado"),
                    ("Rechazado", "Rechazado"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
